package com.hulian.huliantecdemo.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_ENTITY".
 */
@Entity
public class UserEntity implements java.io.Serializable {

    @Id
    private Long id;
    private String user_id;
    private String user_name;

    @Generated
    public UserEntity() {
    }

    public UserEntity(Long id) {
        this.id = id;
    }

    @Generated
    public UserEntity(Long id, String user_id, String user_name) {
        this.id = id;
        this.user_id = user_id;
        this.user_name = user_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

}
